*&---------------------------------------------------------------------*
*& Include          Z_NET_TYPES
*&---------------------------------------------------------------------*

tables:
  mara,
  marc,
  mard,
  rmcp3,
  scal,
  mdez.

types: begin of ty_weeks,
         calendarweek type num2,
         yearweek     type num6,
         total_week   type num2,
       end of ty_weeks.

types: begin of ty_months,
         calendarmonth type num2,
         yearmonth     type num6,
         total_month   type num2,
       end of ty_months.

types: begin of ty_display,
         line_colour(4) type c,
         matnr(35)      type c,
         maktx          type text40,
         dispo          type char4,    " MRP
         resvp          type char3,
         vrmod          type char1,
         vint2          type char3,
         vint1          type char3,
         eisbe          type char9,
         col1(35)       type c,     " Partnumber
         menge          type   p decimals 0,    " Quantity
         past           type   p decimals 0,    " Before week 1
         week01         type   p decimals 0,
         week02         type   p decimals 0,
         week03         type   p decimals 0,
         week04         type   p decimals 0,
         week05         type   p decimals 0,
         week06         type   p decimals 0,
         week07         type   p decimals 0,
         week08         type   p decimals 0,
         week09         type   p decimals 0,
         week10         type   p decimals 0,
         week11         type   p decimals 0,
         week12         type   p decimals 0,
         week13         type   p decimals 0,
         week14         type   p decimals 0,
         week15         type   p decimals 0,
         week16         type   p decimals 0,
         week17         type   p decimals 0,
         week18         type   p decimals 0,
         week19         type   p decimals 0,
         week20         type   p decimals 0,
         week21         type   p decimals 0,
         week22         type   p decimals 0,
         week23         type   p decimals 0,
         week24         type   p decimals 0,
         week25         type   p decimals 0,
         week26         type   p decimals 0,
         week27         type   p decimals 0,
         week28         type   p decimals 0,
         week29         type   p decimals 0,
         week30         type   p decimals 0,
         week31         type   p decimals 0,
         week32         type   p decimals 0,
         week33         type   p decimals 0,
         week34         type   p decimals 0,
         week35         type   p decimals 0,
         week36         type   p decimals 0,
         week37         type   p decimals 0,
         week38         type   p decimals 0,
         week39         type   p decimals 0,
         week40         type   p decimals 0,
         week41         type   p decimals 0,
         week42         type   p decimals 0,
         week43         type   p decimals 0,
         week44         type   p decimals 0,
         week45         type   p decimals 0,
         week46         type   p decimals 0,
         week47         type   p decimals 0,
         week48         type   p decimals 0,
         week49         type   p decimals 0,
         week50         type   p decimals 0,
         week51         type   p decimals 0,
         week52	        type   p decimals 0,
         week53         type   p decimals 0,
         week54         type   p decimals 0,
         week55         type   p decimals 0,
         week56         type   p decimals 0,
         week57         type   p decimals 0,
         week58         type   p decimals 0,
         week59         type   p decimals 0,
         week60         type   p decimals 0,
         week61         type   p decimals 0,
         week62         type   p decimals 0,
         week63         type   p decimals 0,
         week64         type   p decimals 0,
         week65         type   p decimals 0,
         week66         type   p decimals 0,
         week67         type   p decimals 0,
         week68         type   p decimals 0,
         week69         type   p decimals 0,
         week70         type   p decimals 0,
         week71         type   p decimals 0,
         week72         type   p decimals 0,
         week73         type   p decimals 0,
         week74         type   p decimals 0,
         week75         type   p decimals 0,
         week76         type   p decimals 0,
         week77         type   p decimals 0,
         week78         type   p decimals 0,
         week79         type   p decimals 0,
         week80         type   p decimals 0,
         week81         type   p decimals 0,
         week82         type   p decimals 0,
         week83         type   p decimals 0,
         week84         type   p decimals 0,
         week85         type   p decimals 0,
         week86         type   p decimals 0,
         week87         type   p decimals 0,
         week88         type   p decimals 0,
         week89         type   p decimals 0,
         week90         type   p decimals 0,
         week91         type   p decimals 0,
         week92         type   p decimals 0,
         week93         type   p decimals 0,
         week94         type   p decimals 0,
         week95         type   p decimals 0,
         week96         type   p decimals 0,
         week97         type   p decimals 0,
         week98         type   p decimals 0,
         week99         type   p decimals 0,
*         week100        type   p decimals 0,
*         week101        type   p decimals 0,
*         week102        type   p decimals 0,
*         week103        type   p decimals 0,
*         week104        type   p decimals 0,
         rest           type   p decimals 0,   " beyond
       end of ty_display.


types: begin of ty_marc,
         matnr like marc-matnr,
         werks like marc-werks,
         dispo like marc-dispo,
*        prgrp LIKE pgmi-prgrp,
         vrmod like marc-vrmod,
         resvp like marc-resvp,
         vint2 like marc-vint2,
         vint1 like marc-vint1,
         eisbe like marc-eisbe,
         maktx like makt-maktx,

       end of ty_marc.

data: week(10) type c.
*      p_workcenter type

data: week0     like scal-week,
      p_work    like crhd-arbpl,
      p_week(2) type p decimals 0,
      p_yweek   type num6,
      p_ymonth  type num6,
      week0_01  like  week0,
      week0_02  like  week0,
      week0_03  like  week0,
      week0_04  like  week0,
      week0_05  like  week0,
      week0_06  like  week0,
      week0_07  like  week0,
      week0_08  like  week0,
      week0_09  like  week0,
      week0_10  like  week0,
      week0_11  like  week0,
      week0_12  like  week0,
      week0_13  like  week0,
      week0_14  like  week0,
      week0_15  like  week0,
      week0_16  like  week0,
      week0_17  like  week0,
      week0_18  like  week0,
      week0_19  like  week0,
      week0_20  like  week0,
      week0_21  like  week0,
      week0_22  like  week0,
      week0_23  like  week0,
      week0_24  like  week0,
      week0_25  like  week0,
      week0_26  like  week0,
      week0_27  like  week0,
      week0_28  like  week0,
      week0_29  like  week0,
      week0_30  like  week0,
      week0_31  like  week0,
      week0_32  like  week0,
      week0_33  like  week0,
      week0_34  like  week0,
      week0_35  like  week0,
      week0_36  like  week0,
      week0_37  like  week0,
      week0_38  like  week0,
      week0_39  like  week0,
      week0_40  like  week0,
      week0_41  like  week0,
      week0_42  like  week0,
      week0_43  like  week0,
      week0_44  like  week0,
      week0_45  like  week0,
      week0_46  like  week0,
      week0_47  like  week0,
      week0_48  like  week0,
      week0_49  like  week0,
      week0_50  like  week0,
      week0_51  like  week0,
      week0_52 	like  week0,
      week0_53  like  week0,
      week0_54  like  week0,
      week0_55  like  week0,
      week0_56  like  week0,
      week0_57  like  week0,
      week0_58  like  week0,
      week0_59  like  week0,
      week0_60  like  week0,
      week0_61  like  week0,
      week0_62  like  week0,
      week0_63  like  week0,
      week0_64  like  week0,
      week0_65  like  week0,
      week0_66  like  week0,
      week0_67  like  week0,
      week0_68  like  week0,
      week0_69  like  week0,
      week0_70  like  week0,
      week0_71  like  week0,
      week0_72  like  week0,
      week0_73  like  week0,
      week0_74  like  week0,
      week0_75  like  week0,
      week0_76  like  week0,
      week0_77  like  week0,
      week0_78  like  week0,
      week0_79  like  week0,
      week0_80  like  week0,
      week0_81  like  week0,
      week0_82  like  week0,
      week0_83  like  week0,
      week0_84  like  week0,
      week0_85  like  week0,
      week0_86  like  week0,
      week0_87  like  week0,
      week0_88  like  week0,
      week0_89  like  week0,
      week0_90  like  week0,
      week0_91  like  week0,
      week0_92  like  week0,
      week0_93  like  week0,
      week0_94  like  week0,
      week0_95  like  week0,
      week0_96  like  week0,
      week0_97  like  week0,
      week0_98  like  week0,
      week0_99  like  week0,
*      week0_100  like  week0,
*      week0_101  like  week0,
*      week0_102  like  week0,
*      week0_103  like  week0,
*      week0_104  like  week0,

      week01    like  week,
      week02    like  week,
      week03    like  week,
      week04    like  week,
      week05    like  week,
      week06    like  week,
      week07    like  week,
      week08    like  week,
      week09    like  week,
      week10    like  week,
      week11    like  week,
      week12    like  week,
      week13    like  week,
      week14    like  week,
      week15    like  week,
      week16    like  week,
      week17    like  week,
      week18    like  week,
      week19    like  week,
      week20    like  week,
      week21    like  week,
      week22    like  week,
      week23    like  week,
      week24    like  week,
      week25    like  week,
      week26    like  week,
      week27    like  week,
      week28    like  week,
      week29    like  week,
      week30    like  week,
      week31    like  week,
      week32    like  week,
      week33    like  week,
      week34    like  week,
      week35    like  week,
      week36    like  week,
      week37    like  week,
      week38    like  week,
      week39    like  week,
      week40    like  week,
      week41    like  week,
      week42    like  week,
      week43    like  week,
      week44    like  week,
      week45    like  week,
      week46    like  week,
      week47    like  week,
      week48    like  week,
      week49    like  week,
      week50    like  week,
      week51    like  week,
      week52    like  week,
      week53    like  week,
      week54    like  week,
      week55    like  week,
      week56    like  week,
      week57    like  week,
      week58    like  week,
      week59    like  week,
      week60    like  week,
      week61    like  week,
      week62    like  week,
      week63    like  week,
      week64    like  week,
      week65    like  week,
      week66    like  week,
      week67    like  week,
      week68    like  week,
      week69    like  week,
      week70    like  week,
      week71    like  week,
      week72    like  week,
      week73    like  week,
      week74    like  week,
      week75    like  week,
      week76    like  week,
      week77    like  week,
      week78    like  week,
      week79    like  week,
      week80    like  week,
      week81    like  week,
      week82    like  week,
      week83    like  week,
      week84    like  week,
      week85    like  week,
      week86    like  week,
      week87    like  week,
      week88    like  week,
      week89    like  week,
      week90    like  week,
      week91    like  week,
      week92    like  week,
      week93    like  week,
      week94    like  week,
      week95    like  week,
      week96    like  week,
      week97    like  week,
      week98    like  week,
      week99    like  week.
*      week100    like  week,
*      week101    like  week,
*      week102    like  week,
*      week103    like  week,
*      week104    like  week.


data: w_dispo type dispo.

data: it_marc type ty_marc occurs 0 with header line,
      wa_marc type ty_marc.

field-groups: it_marc2.

data gt_weeks type ty_weeks occurs 0.
data gt_months type ty_months occurs 0.

data: t_display   type ty_display occurs 0,
      wa_display  type ty_display,
      wa_displayx type ty_display, "used for calculations
      wa_display1 type ty_display, "MD04 PIR + SA
      wa_display2 type ty_display, "Open Production
      wa_display3 type ty_display, "Open PO
      wa_display4 type ty_display, "In Transit
      wa_display5 type ty_display, "In Plant
      wa_display6 type ty_display,
      wa_display7 type ty_display, "Delivery
      wa_display8 type ty_display. "Dep. Requirements


data: i_mdez  like mdez occurs 0 with header line,
      i_mdsta like mdsta occurs 0 with header line.

data i_exit.

include: <icon>.

type-pools: slis,
            cntb.

* ALV layout definities.
data: t_fieldcat   type lvc_t_fcat,
      field_tab    type slis_t_fieldcat_alv,
      wa_field_tab type slis_fieldcat_alv.

* Algemene data.
data: okcode            type syst-ucomm.

data: c_true  type boolean value 'X',
      c_false type boolean value ''.
